app = 'db-test-mysql'
primary_region = 'nrt'

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "3000"
  NODE_ENV = "production"
  PRIMARY_REGION = "nrt"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 200
    soft_limit = 150
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"